insert into lessons
  (language_id,   title_en,                    slug,                        sort_order,   created_by ) values
  ('it',          'Articles',                  'articles',                  10,           'USER_ID'  ),
  ('it',          'Cognates',                  'cognates',                  10,           'USER_ID'  ),
  ('it',          'Gender',                    'gender',                    10,           'USER_ID'  ),
  ('it',          'Greetings',                 'greetings',                 10,           'USER_ID'  ),
  ('it',          'Language',                  'language',                  10,           'USER_ID'  ),
  ('it',          'Polite basics',             'polite basics',             10,           'USER_ID'  ),
  ('it',          'Alphabet',                  'alphabet',                  20,           'USER_ID'  ),
  ('it',          'Colors',                    'colors',                    20,           'USER_ID'  ),
  ('it',          'Comparative adjectives',    'comparative-adjectives',    20,           'USER_ID'  ),
  ('it',          'Conditionals',              'conditionals',              20,           'USER_ID'  ),
  ('it',          'Describing objects',        'describing-objects',        20,           'USER_ID'  ),
  ('it',          'Describing people',         'describing-people',         20,           'USER_ID'  ),
  ('it',          'Eating',                    'eating',                    20,           'USER_ID'  ),
  ('it',          'Emergencies',               'emergencies',               20,           'USER_ID'  ),
  ('it',          'Family',                    'family',                    20,           'USER_ID'  ),
  ('it',          'Getting around',            'getting-around',            20,           'USER_ID'  ),
  ('it',          'Irregular verbs',           'irregular-verbs',           20,           'USER_ID'  ),
  ('it',          'Numbers 11-100',            'numbers-11-100',            20,           'USER_ID'  ),
  ('it',          'Numbers',                   'numbers',                   20,           'USER_ID'  ),
  ('it',          'Plurals',                   'plurals',                   20,           'USER_ID'  ),
  ('it',          'Possessives',               'possessives',               20,           'USER_ID'  ),
  ('it',          'Pronunciation',             'pronunciation',             20,           'USER_ID'  ),
  ('it',          'Questions',                 'questions',                 20,           'USER_ID'  ),
  ('it',          'Senses',                    'senses',                    20,           'USER_ID'  ),
  ('it',          'Time and date',             'time-and-date',             20,           'USER_ID'  ),
  ('it',          'Top 1000 words',            'top-1000-words',            20,           'USER_ID'  ),
  ('it',          'Animals',                   'animals',                   30,           'USER_ID'  ),
  ('it',          'Art',                       'art',                       30,           'USER_ID'  ),
  ('it',          'Big numbers',               'big-numbers',               30,           'USER_ID'  ),
  ('it',          'Body parts',                'body-parts',                30,           'USER_ID'  ),
  ('it',          'Clothing',                  'clothing',                  30,           'USER_ID'  ),
  ('it',          'Coffee and tea',            'coffee-and-tea',            30,           'USER_ID'  ),
  ('it',          'Cooking',                   'cooking',                   30,           'USER_ID'  ),
  ('it',          'Emotions',                  'emotions',                  30,           'USER_ID'  ),
  ('it',          'Holidays',                  'holidays',                  30,           'USER_ID'  ),
  ('it',          'Houses and buildings',      'houses-and-buildings',      30,           'USER_ID'  ),
  ('it',          'Italian history',           'italian-history',           30,           'USER_ID'  ),
  ('it',          'Italian places',            'italian-places',            30,           'USER_ID'  ),
  ('it',          'Love',                      'love',                      30,           'USER_ID'  ),
  ('it',          'Math and science',          'math-and-science',          30,           'USER_ID'  ),
  ('it',          'Music',                     'music',                     30,           'USER_ID'  ),
  ('it',          'Names',                     'names',                     30,           'USER_ID'  ),
  ('it',          'Politics',                  'politics',                  30,           'USER_ID'  ),
  ('it',          'Profanity',                 'profanity',                 30,           'USER_ID'  ),
  ('it',          'Shopping',                  'shopping',                  30,           'USER_ID'  ),
  ('it',          'The outdoors',              'outdoors',                  30,           'USER_ID'  ),
  ('it',          'Weather',                   'weather',                   30,           'USER_ID'  ),
  ('it',          'Working',                   'working',                   30,           'USER_ID'  ),
  ('it',          'Dialects',                  'dialects',                  40,           'USER_ID'  ),
  ('it',          'Movie quotes',              'movie-quotes',              40,           'USER_ID'  );
