insert into topics
  (slug,                user_selectable,  title_eng,          description_eng,                                          created_by ) values
  ('basics',            false,            'Basics',           'Basic words and phrases to get you started',             'USER_ID'  ),
  ('pronounciation',    false,            'Pronounciation',   'Learning to say words in Italian correctly',             'USER_ID'  ),
  ('verbs',             false,            'Verbs',            'How to describe actions and doing things',               'USER_ID'  ),
  ('objects',           false,            'Objects',          'How to describe objects',                                'USER_ID'  ),
  ('food',              true,             'Food',             'Eating, drinking, cooking, and dining out',              'USER_ID'  ),
  ('romance',           true,             'Romance',          'Dating, flirting, marraige, and romantic relationships', 'USER_ID'  ),
  ('family',            true,             'Family',           'Talking to relatives, researching ancestors',            'USER_ID'  ),
  ('work',              true,             'Work',             'Professional conversations and business',                'USER_ID'  ),
  ('grammar',           false,            'Grammar',          'Conjugation, sentence construction, etc',                'USER_ID'  ),
  ('cognates',          false,            'Cognates',         'Words that are similar to other languages',              'USER_ID'  ),
  ('gender',            false,            'Gender',           'How to use gendered words correctly in Italian',         'USER_ID'  ),
  ('travel',            true,             'Travel',           'Flights, hotels, and getting around',                    'USER_ID'  ),
  ('people',            false,            'People',           'How to talk about people',                               'USER_ID'  ),
  ('numbers',           false,            'Numbers',          'Numbers, counting, and money',                           'USER_ID'  ),
  ('questions',         false,            'Questions',        'Asking questions',                                       'USER_ID'  ),
  ('time',              false,            'Time',             'Time of day, weeks, months, and seasons',                'USER_ID'  ),
  ('nature',            true,             'Nature',           'Talking about nature',                                   'USER_ID'  ),
  ('tenses',            false,            'Tenses',           'Things in the past and future',                          'USER_ID'  ),
  ('arts',              true,             'Arts',             'Arts and music',                                         'USER_ID'  ),
  ('emotions',          false,            'Emotions',         'Describing emotions and feeling',                        'USER_ID'  ),
  ('geography',         true,             'Geography',        'Geography of the world, and especially Italy',           'USER_ID'  ),
  ('dialects',          false,            'Dialects',         'Differences in Italian dialects',                        'USER_ID'  ),
  ('culture',           true,             'Culture',          'Italian culture and history, including Roman history',   'USER_ID'  );
