insert into topics
  (id,                  title_en,           description_en,                                           created_by ) values
  ('basics',            'Basics',           'Basic words and phrases to get you started',             'USER_ID'  ),
  ('pronounciation',    'Pronounciation',   'Learning to say words in Italian correctly',             'USER_ID'  ),
  ('verbs',             'Verbs',            'How to describe actions and doing things',               'USER_ID'  ),
  ('objects',           'Objects',          'How to describe objects',                                'USER_ID'  ),
  ('food',              'Food',             'Eating, drinking, cooking, and dining out',              'USER_ID'  ),
  ('romance',           'Romance',          'Dating, flirting, marraige, and romantic relationships', 'USER_ID'  ),
  ('family',            'Family',           'Talking to relatives, researching ancestors',            'USER_ID'  ),
  ('work',              'Work',             'Professional conversations and business',                'USER_ID'  ),
  ('grammar',           'Grammar',          'Conjugation, sentence construction, etc',                'USER_ID'  ),
  ('cognates',          'Cognates',         'Words that are similar to other languages',              'USER_ID'  ),
  ('gender',            'Gender',           'How to use gendered words correctly in Italian',         'USER_ID'  ),
  ('travel',            'Travel',           'Flights, hotels, and getting around',                    'USER_ID'  ),
  ('people',            'People',           'How to talk about people',                               'USER_ID'  ),
  ('numbers',           'Numbers',          'Numbers, counting, and money',                           'USER_ID'  ),
  ('questions',         'Questions',        'Asking questions',                                       'USER_ID'  ),
  ('time',              'Time',             'Time of day, weeks, months, and seasons',                'USER_ID'  ),
  ('nature',            'Nature',           'Talking about nature',                                   'USER_ID'  ),
  ('tenses',            'Tenses',           'Things in the past and future',                          'USER_ID'  ),
  ('arts',              'Arts',             'Arts and music',                                         'USER_ID'  ),
  ('emotions',          'Emotions',         'Describing emotions and feeling',                        'USER_ID'  ),
  ('geography',         'Geography',        'Geography of the world, and especially Italy',           'USER_ID'  ),
  ('dialects',          'Dialects',         'Differences in Italian dialects',                        'USER_ID'  ),
  ('culture',           'Culture',          'Italian culture and history, including Roman history',   'USER_ID'  );
